qa update
git-svn-id: svn://svn.caucho.com/resin/trunk@1903 9c94448d-38f1-0310-a231-d98308ff1ebf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8335,6 +8335,12 @@ if test "${apache_dir}" = "yes"; then
   apache_dir=/usr/local/apache
 fi
 
+if test ! -d "${apache_dir}; then
+  { { echo "$as_me:$LINENO: error: --with-apache=${apache_dir} is not a valid Apache directory" >&5
+echo "$as_me: error: --with-apache=${apache_dir} is not a valid Apache directory" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 apache=1
 
 fi;
@@ -8708,7 +8714,7 @@ echo -n "checking if Java is 64-bit... "
 tmpname="/tmp/java$$.out"
 
 $JAVA_HOME/bin/java -version 2> $tmpname
-grep -E "(64-Bit|amd64-64)" $tmpname 1> /dev/null
+grep "(64-Bit|amd64-64)" $tmpname 1> /dev/null
 
 if test "$?" = "0"; then
    b64_jni=true
@@ -8806,7 +8812,7 @@ if test -z "${LD_SHLIB}"; then
 	if test -n "$is_gnu_ld"; then
 	    LDFLAGS_SHLIB="-shared"
         else
-	    LDFLAGS_SHLIB="-G"
+	    LDFLAGS_SHLIB="-G -fPIC"
 	fi
 	;;
 
